# This workflow executes the E2E Test Suite for a series of combinations that
# represent different execution environments
name: continuous-delivery
on:
  workflow_dispatch:
    inputs:
      depth:
        description: 'Depth (push, pull_request, main (default), schedule)'
        required: true
        default: 'main'
      limit:
        description: 'Limit to the specified engines list (local, eks, aks, gke, openshift)'
        required: false
      test_level:
        description: 'Test level: 0(highest) to 4(lowest). Default is 4.'
        required: false
        default: '4'
      feature_type:
        description: >
          Feature Type (backup-restore, basic, cluster-metadata, declarative-databases, disruptive,
          importing-databases, maintenance, no-openshift, observability, operator, performance, plugin,
          pod-scheduling, postgres-configuration, postgres-major-upgrade, publication-subscription, recovery,
          replication, security, self-healing, service-connectivity, smoke, snapshot, storage, tablespaces, upgrade)
        required: false
      log_level:
        description: 'Log level for operator (error, warning, info, debug(default), trace)'
        required: false
        default: 'debug'

permissions: read-all

# set up environment variables to be used across all the jobs
env:
  # renovate: datasource=golang-version depName=golang versioning=loose
  GOLANG_VERSION: "1.25.2"
  KUBEBUILDER_VERSION: "2.3.1"
  # renovate: datasource=github-tags depName=kubernetes-sigs/kind versioning=semver
  KIND_VERSION: "v0.30.0"
  # renovate: datasource=github-releases depName=rook/rook versioning=loose
  ROOK_VERSION: "v1.18.4"
  EXTERNAL_SNAPSHOTTER_VERSION: "v8.3.0"
  OPERATOR_IMAGE_NAME: "ghcr.io/${{ github.repository }}-testing"
  BUILD_PUSH_PROVENANCE: ""
  BUILD_PUSH_CACHE_FROM: ""
  BUILD_PUSH_CACHE_TO: ""
  REGISTRY: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY_OWNER: "cloudnative-pg"
  SIGN_IMAGES: "true"
  SLACK_USERNAME: "cnpg-bot"
  BUILD_MANAGER_RELEASE_ARGS: "build --skip=validate --clean --id manager"
  # Keep in mind that adding more platforms (architectures) will increase the building
  # time even if we use the ghcache for the building process.
  PLATFORMS: "linux/amd64"
  E2E_SUFFIX: "cnpge2e"

defaults:
  run:
    # default failure handling for shell scripts in 'run' steps
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  # Trigger the workflow on release-* branches for smoke testing whenever it's a scheduled run.
  # Note: this is a workaround since we can't directly schedule-run a workflow from a non default branch
  smoke_test_release_branches:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    name: smoke test release-* branches when it's a scheduled run
    if: github.event_name == 'schedule'
    strategy:
      fail-fast: false
      matrix:
        branch: [release-1.25, release-1.26, release-1.27]
    steps:
      - name: Invoke workflow with inputs
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1
        with:
          workflow: continuous-delivery
          ref: ${{ matrix.branch }}
          inputs: '{ "depth": "push", "limit": "local", "test_level": "4", "log_level": "debug" }'

  check_commenter:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.action == 'created' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/test')
    name: Retrieve command
    permissions:
      pull-requests: write
      contents: read
      issues: read
    runs-on: ubuntu-24.04
    outputs:
      github_ref: ${{ steps.refs.outputs.head_sha }}
      depth: ${{ env.DEPTH }}
      limit: ${{ env.LIMIT }}
      test_level: ${{ env.TEST_LEVEL }}
      feature_type: ${{ env.FEATURE_TYPE }}
      log_level: ${{ env.LOG_LEVEL }}
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@bf51f8f5f4ea3d58abc7eca58f77104182b23e88 # v2
        continue-on-error: false
        with:
          command: test
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write

      - name: Process arguments
        id: args
        run: |
          ARGS="${{ steps.command.outputs.command-arguments }}"
          # Set the defaults
          DEPTH="main"
          LIMIT="local"
          TEST_LEVEL="4"
          FEATURE_TYPE=""
          LOG_LEVEL="debug"

          for ARG in $ARGS; do
            IFS='=' read name value <<< $ARG
            case "${name}" in
              "depth"|"d")
              DEPTH="${value}"
              ;;
              "limit"|"l")
              LIMIT="${value}"
              ;;
              "test_level"|"level"|"tl")
              TEST_LEVEL="${value}"
              ;;
              "feature_type"|"type"|"ft")
              FEATURE_TYPE="${value}"
              ;;
              "log_level"|"ll")
              LOG_LEVEL="${value}"
              ;;
              *)
              ;;
            esac
          done

          echo "DEPTH=${DEPTH}" >> $GITHUB_ENV
          echo "LIMIT=${LIMIT}" >> $GITHUB_ENV
          echo "TEST_LEVEL=${TEST_LEVEL}" >> $GITHUB_ENV
          echo "FEATURE_TYPE=${FEATURE_TYPE}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${LOG_LEVEL}" >> $GITHUB_ENV

      - name: Resolve Git reference
        uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1 # v3
        id: refs

      - name: Create comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.actor }}, here's the link to the E2E on CNPG workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test_arguments:
    name: Parse arguments
    if: |
      github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    runs-on: ubuntu-24.04
    outputs:
      github_ref: ${{ github.ref }}
      depth: ${{ env.DEPTH }}
      limit: ${{ env.LIMIT }}
      test_level: ${{ env.TEST_LEVEL }}
      feature_type: ${{ env.FEATURE_TYPE }}
      log_level: ${{ env.LOG_LEVEL }}
    steps:
      - name: Parse input to env
        run: |
          # Set the defaults for workflow dispatch
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            DEPTH=${{ github.event.inputs.depth }}
            LIMIT=${{ github.event.inputs.limit }}
            TEST_LEVEL=${{ github.event.inputs.test_level }}
            FEATURE_TYPE="${{ github.event.inputs.feature_type }}"
            LOG_LEVEL="${{ github.event.inputs.log_level }}"
          fi
          # Set the defaults for schedule dispatch
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            DEPTH="schedule"
            LIMIT=""
            TEST_LEVEL="4"
            FEATURE_TYPE=""
            LOG_LEVEL="debug"
          fi
          echo "DEPTH=${DEPTH}" >> $GITHUB_ENV
          echo "LIMIT=${LIMIT}" >> $GITHUB_ENV
          echo "TEST_LEVEL=${TEST_LEVEL}" >> $GITHUB_ENV
          echo "FEATURE_TYPE=${FEATURE_TYPE}" >> $GITHUB_ENV
          echo "LOG_LEVEL=${LOG_LEVEL}" >> $GITHUB_ENV

  evaluate_options:
    name: Evaluate workflow options
    needs:
      - check_commenter
      - test_arguments
    runs-on: ubuntu-24.04
    if: |
      (
        needs.check_commenter.result == 'success' ||
        needs.test_arguments.result == 'success'
      ) &&
      !cancelled()
    outputs:
      git_ref: ${{ env.GITHUB_REF }}
      depth: ${{ env.DEPTH }}
      limit: ${{ env.LIMIT }}
      test_level: ${{ env.TEST_LEVEL }}
      feature_type: ${{ env.FEATURE_TYPE }}
      log_level: ${{ env.LOG_LEVEL }}
    steps:
      - name: From command
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]] || [[ ${{ github.event_name }} == 'schedule' ]]; then
            echo 'GITHUB_REF=${{ needs.test_arguments.outputs.github_ref }}' >> $GITHUB_ENV
            echo 'DEPTH=${{ needs.test_arguments.outputs.depth }}' >> $GITHUB_ENV
            echo 'LIMIT=${{ needs.test_arguments.outputs.limit }}' >> $GITHUB_ENV
            echo 'TEST_LEVEL=${{ needs.test_arguments.outputs.test_level }}' >> $GITHUB_ENV
            echo 'FEATURE_TYPE=${{ needs.test_arguments.outputs.feature_type }}' >> $GITHUB_ENV
            echo 'LOG_LEVEL=${{ needs.test_arguments.outputs.log_level }}' >> $GITHUB_ENV
          fi
          if [[ ${{ github.event_name }} == 'issue_comment' ]]; then
            echo 'GITHUB_REF=${{ needs.check_commenter.outputs.github_ref }}' >> $GITHUB_ENV
            echo 'DEPTH=${{ needs.check_commenter.outputs.depth }}' >> $GITHUB_ENV
            echo 'LIMIT=${{ needs.check_commenter.outputs.limit }}' >> $GITHUB_ENV
            echo 'TEST_LEVEL=${{ needs.check_commenter.outputs.test_level }}' >> $GITHUB_ENV
            echo 'FEATURE_TYPE=${{ needs.check_commenter.outputs.feature_type }}' >> $GITHUB_ENV
            echo 'LOG_LEVEL=${{ needs.check_commenter.outputs.log_level }}' >> $GITHUB_ENV
          fi

  buildx:
    name: Build containers
    needs:
      - check_commenter
      - test_arguments
      - evaluate_options
    if: |
      always() && !cancelled() &&
      needs.evaluate_options.result == 'success'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      pull-requests: read
      id-token: write
    outputs:
      # 'branch_name' is used in 'GetMostRecentReleaseTag' in the Go code
      branch_name: ${{ steps.build-meta.outputs.branch_name }}
      upload_artifacts: ${{ steps.build-meta.outputs.upload_artifacts }}
      commit_msg: ${{ steps.build-meta.outputs.commit_msg }}
      commit_sha: ${{ steps.build-meta.outputs.commit_sha }}
      author_name: ${{ steps.build-meta.outputs.author_name }}
      author_email: ${{ steps.build-meta.outputs.author_email }}
      controller_img: ${{ env.CONTROLLER_IMG }}
      controller_img_digest: ${{ fromJSON(steps.bake-push.outputs.metadata)['distroless']['containerimage.digest'] }}
      controller_img_prime_digest: ${{ steps.build-prime.outputs.digest }}
      controller_img_ubi: ${{ env.CONTROLLER_IMG_UBI }}
      index_img: ${{ env.INDEX_IMG }}
      bundle_img: ${{ env.BUNDLE_IMG }}
      catalog_img: ${{ env.CATALOG_IMG }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ needs.evaluate_options.outputs.git_ref }}
          # To identify the commit we need the history and all the tags.
          fetch-depth: 0
      -
        name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          check-latest: true
      -
        name: Build meta
        id: build-meta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha=${{ needs.evaluate_options.outputs.git_ref }}
          commit_date=$(git log -1 --pretty=format:'%ad' --date short "${commit_sha}" || : )
          # use git describe to get the nearest tag and use that to build the version (e.g. 1.4.0-dev24 or 1.4.0)
          commit_version=$(git describe --tags --match 'v*' "${commit_sha}"| sed -e 's/^v//; s/-g[0-9a-f]\+$//; s/-\([0-9]\+\)$/-dev\1/')

          # shortened commit sha
          commit_short=$(git rev-parse --short "${commit_sha}")

          # multiline strings are weird
          commit_message=$(git show -s --format=%B "${commit_sha}")
          commit_message=${commit_message//$'%'/'%25'}
          commit_message=${commit_message//$'\n'/'%0A'}
          commit_message=${commit_message//$'\r'/'%0D'}

          # get git user and email
          author_name=$(git show -s --format='%an' "${commit_sha}")
          author_email=$(git show -s --format='%ae' "${commit_sha}")

          # extract branch name
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]] || [[ ${{ github.event_name }} == 'schedule' ]]
          then
            branch_name=${GITHUB_REF#refs/heads/}
          fi
          if [[ ${{ github.event_name }} == 'issue_comment' ]]
          then
            branch_name=$(gh pr view "${{ github.event.issue.number }}" --json headRefName -q '.headRefName' 2>/dev/null)
          fi

          # extract tag from branch name
          tag_name=$(echo "$branch_name" | tr / -)

          upload_artifacts=false
          if [[ ${branch_name} == main || ${branch_name} =~ ^release- ]]; then
            upload_artifacts=true
          fi

          echo "DATE=${commit_date}" >> $GITHUB_ENV
          echo "VERSION=${commit_version}" >> $GITHUB_ENV
          echo "COMMIT=${commit_short}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${tag_name,,}" >> $GITHUB_ENV
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "commit_sha=${commit_sha}" >> $GITHUB_OUTPUT
          echo "commit_msg=${commit_message}" >> $GITHUB_OUTPUT
          echo "author_name=${author_name}" >> $GITHUB_OUTPUT
          echo "author_email=${author_email}" >> $GITHUB_OUTPUT
          echo "branch_name=${branch_name}" >> $GITHUB_OUTPUT
          echo "upload_artifacts=${upload_artifacts}" >> $GITHUB_OUTPUT
      -
        name: Set GoReleaser environment
        run: |
          echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
          echo PWD=$(pwd) >> $GITHUB_ENV
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: v2
          args: ${{ env.BUILD_MANAGER_RELEASE_ARGS }}
        env:
          DATE: ${{ env.DATE }}
          COMMIT: ${{ env.COMMIT }}
          VERSION: ${{ env.VERSION }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: ${{ env.PLATFORMS }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      -
        name: Login into docker registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6
        id: bake-push
        env:
          environment: "testing"
          buildVersion: ${{ env.VERSION }}
          tag: ${{ env.IMAGE_TAG }}
          registry: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}
          revision: ${{ env.COMMIT }}
        with:
          source: .
          push: true
          no-cache: true
          targets: "default"
      -
        name: Install cosign
        if: env.SIGN_IMAGES == 'true'
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3
        # See https://github.blog/security/supply-chain-security/safeguard-container-signing-capability-actions/
        # and https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml for more details on
        # how to use cosign.
      -
        name: Sign images
        if: env.SIGN_IMAGES == 'true'
        run: |
          images=$(echo '${{ steps.bake-push.outputs.metadata }}' |
            jq -r '.[] | (."image.name" | sub(",.*";"" )) + "@" + ."containerimage.digest"'
          )
          cosign sign --yes ${images}
      -
        name: Output images
        env:
          DISTROLESS: ${{ fromJSON(steps.bake-push.outputs.metadata)['distroless']['image.name'] }}
          UBI: ${{ fromJSON(steps.bake-push.outputs.metadata)['ubi']['image.name'] }}
        run: |
          echo "CONTROLLER_IMG=${DISTROLESS}" >> $GITHUB_ENV
          echo "CONTROLLER_IMG_UBI=${UBI}" >> $GITHUB_ENV
          echo "BUNDLE_IMG=${UBI}-bundle" >> $GITHUB_ENV
          echo "INDEX_IMG=${UBI}-index" >> $GITHUB_ENV
          echo "CATALOG_IMG=${UBI}-catalog" >> $GITHUB_ENV
      -
        name: Generate manifest for operator deployment
        id: generate-manifest
        env:
          CONTROLLER_IMG: ${{ env.CONTROLLER_IMG }}
          CONTROLLER_IMG_DIGEST: ${{ fromJSON(steps.bake-push.outputs.metadata)['distroless']['containerimage.digest'] }}
        run: |
          make generate-manifest
      -
        name: Upload the operator manifest as artifact in workflow
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: operator-manifest.yaml
          path: dist/operator-manifest.yaml
          retention-days: 10
      -
      # In order to test the case of upgrading from the current operator
      # to a future one, we build and push an image with a different VERSION
      # to force a different hash for the manager binary.
      # (Otherwise the ONLINE upgrade won't trigger)
      #
      # NOTE: we only fire this in TEST DEPTH = 4, as that is the level of the
      # upgrade test
        name: Build binary for upgrade test
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        if: |
          always() && !cancelled() &&
          needs.evaluate_options.outputs.test_level == '4'
        with:
          distribution: goreleaser
          version: v2
          args: ${{ env.BUILD_MANAGER_RELEASE_ARGS }}
        env:
          DATE: ${{ env.DATE }}
          COMMIT: ${{ env.COMMIT }}
          VERSION: ${{ env.VERSION }}-prime
      -
      # In order to test the case of upgrading from the current operator
      # to a future one, we build and push an image with a different VERSION
      # to force a different hash for the manager binary.
      # (Otherwise the ONLINE upgrade won't trigger)
      #
      # We push the "prime" binary using a tag with the suffix "-prime"
      # NOTE: we only fire this in TEST DEPTH = 4, as that is the level of the
      # upgrade test
        name: Build and push image for upgrade test
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        id: build-prime
        if: |
          always() && !cancelled() &&
          needs.evaluate_options.outputs.test_level == '4'
        with:
          platforms: ${{ env.PLATFORMS }}
          context: .
          file: Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}-prime
          tags: ${{ env.CONTROLLER_IMG }}-prime
          provenance: ${{ env.BUILD_PUSH_PROVENANCE }}
          cache-from: ${{ env.BUILD_PUSH_CACHE_FROM }}
          cache-to: ${{ env.BUILD_PUSH_CACHE_TO }}

  generate-jobs:
    name: Generate jobs for E2E tests
    needs:
      - buildx
      - evaluate_options
    # We try to avoid running the E2E Test Suite in general, to reduce load on
    # GitHub resources.
    # Currently, it's executed in the following cases:
    # - When dispatched via chatops commands
    # - On a push in main and release branches
    # - On scheduled executions
    if: |
      (always() && !cancelled()) &&
      needs.buildx.result == 'success'
    runs-on: ubuntu-24.04
    outputs:
      controller_img: ${{ needs.buildx.outputs.controller_img }}
      localMatrix: ${{ steps.generate-jobs.outputs.localMatrix }}
      localEnabled: ${{ steps.generate-jobs.outputs.localEnabled }}
      localTimeout: ${{ steps.generate-jobs.outputs.localE2ETimeout }}
      eksMatrix: ${{ steps.generate-jobs.outputs.eksMatrix }}
      eksEnabled: ${{ steps.generate-jobs.outputs.eksEnabled }}
      eksTimeout: ${{ steps.generate-jobs.outputs.eksE2ETimeout }}
      aksMatrix: ${{ steps.generate-jobs.outputs.aksMatrix }}
      aksEnabled: ${{ steps.generate-jobs.outputs.aksEnabled }}
      aksTimeout: ${{ steps.generate-jobs.outputs.aksE2ETimeout }}
      gkeMatrix: ${{ steps.generate-jobs.outputs.gkeMatrix }}
      gkeEnabled: ${{ steps.generate-jobs.outputs.gkeEnabled }}
      gkeTimeout: ${{ steps.generate-jobs.outputs.gkeE2ETimeout }}
      openshiftMatrix: ${{ steps.generate-jobs.outputs.openshiftMatrix }}
      openshiftEnabled: ${{ steps.generate-jobs.outputs.openshiftEnabled }}
      openshiftTimeout: ${{ steps.generate-jobs.outputs.openshiftE2ETimeout }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ needs.evaluate_options.outputs.git_ref }}
      -
        id: generate-jobs
        # Generates the jobs that will become different matrix branches,
        # according to the event, or to the "depth" parameter if set manually
        name: Generate Jobs
        shell: bash
        run: |
          python .github/e2e-matrix-generator.py \
            -m '${{ needs.evaluate_options.outputs.depth }}' \
            -l '${{ needs.evaluate_options.outputs.limit }}'

  e2e-local:
    name: Run E2E on local executors
    if: |
      (always() && !cancelled()) &&
      needs.generate-jobs.outputs.localEnabled == 'true' &&
      needs.generate-jobs.result == 'success'
    needs:
      - buildx
      - generate-jobs
      - evaluate_options
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-jobs.outputs.localMatrix) }}
    runs-on: ubuntu-24.04
    env:
      # TEST_DEPTH determines the maximum test level the suite should be running
      TEST_DEPTH: ${{ needs.evaluate_options.outputs.test_level }}
      # FEATURE_TYPE, when defined, determines the subset of E2E tests that will be executed, divided by feature type
      FEATURE_TYPE: ${{ needs.evaluate_options.outputs.feature_type }}

      K8S_VERSION: "${{ matrix.k8s_version }}"
      POSTGRES_VERSION: ${{ matrix.postgres_version }}
      POSTGRES_KIND: ${{ matrix.postgres_kind }}
      MATRIX: ${{ matrix.id }}
      POSTGRES_IMG: "${{ matrix.postgres_img }}"
      # The version of operator to upgrade FROM, in the rolling upgrade E2E test
      E2E_PRE_ROLLING_UPDATE_IMG: "${{ matrix.postgres_pre_img }}"
      TEST_TIMEOUTS: ${{ needs.generate-jobs.outputs.localTimeout }}
      BRANCH_NAME: ${{ needs.buildx.outputs.branch_name }}

      DEBUG: "true"
      BUILD_IMAGE: "false"
      CONTROLLER_IMG: ${{ needs.generate-jobs.outputs.controller_img }}
      CONTROLLER_IMG_DIGEST: ${{ needs.buildx.outputs.controller_img_digest }}
      CONTROLLER_IMG_PRIME_DIGEST: ${{ needs.buildx.outputs.controller_img_prime_digest }}
      E2E_DEFAULT_STORAGE_CLASS: standard
      E2E_CSI_STORAGE_CLASS: csi-hostpath-sc
      E2E_DEFAULT_VOLUMESNAPSHOT_CLASS: csi-hostpath-snapclass
      LOG_DIR: ${{ github.workspace }}/kind-logs/
      DOCKER_REGISTRY_MIRROR: https://mirror.gcr.io
      TEST_CLOUD_VENDOR: "local"
    steps:
      -
        name: Cleanup Disk
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          tool-cache: true
          large-packages: false
          swap-storage: false
      -
        name: Cleanup docker cache
        run: |
          echo "-------------Disk info before cleanup----------------"
          df -h
          echo "-----------------------------------------------------"
          docker system prune -a -f
          echo "-------------Disk info after cleanup----------------"
          df -h
          echo "-----------------------------------------------------"
      -
        name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ needs.evaluate_options.outputs.git_ref }}
      -
        name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          check-latest: true
      -
        ## In case hack/setup-cluster.sh need pull operand image from registry
        name: Login into docker registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      -
        name: Install Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          version: ${{ env.KIND_VERSION }}
          kubectl_version: ${{ env.K8S_VERSION }}
      -
        name: Prepare patch for customization
        env:
          ## the following variable all need be set if we use env_override_customized.yaml.template
          ## this is customization for local kind
          LEADER_ELECTION: "true"
          LEADER_LEASE_DURATION: 15
          LEADER_RENEW_DEADLINE: 10
          LIVENESS_PROBE_THRESHOLD: 3
          LOG_LEVEL: ${{ needs.evaluate_options.outputs.log_level }}
        run: |
          LOG_LEVEL=${LOG_LEVEL:-info}
          envsubst < hack/e2e/env_override_customized.yaml.template > config/manager/env_override.yaml
          cat config/manager/env_override.yaml
      -
        name: Run Kind End-to-End tests
        env:
          ENABLE_APISERVER_AUDIT: true
        run:
          make e2e-test-kind
      -
        # Summarize the failed E2E test cases if there are any
        name: Report failed E2E tests
        if: failure()
        run: |
          set +x
          chmod +x .github/report-failed-test.sh
          ./.github/report-failed-test.sh
      -
        # Create an individual artifact for each E2E test, which will be used to
        # generate E2E test summary in the follow-up job 'summarize-e2e-tests'
        name: Create individual artifact for each E2E test
        if: (always() && !cancelled())
        env:
          RUNNER: "local"
          RUN_ID: ${{ github.run_id }}
          REPOSITORY: ${{ github.repository }}
          GIT_REF: ${{ needs.evaluate_options.outputs.git_ref }}
        run: |
          set +x
          python .github/generate-test-artifacts.py \
            -o testartifacts-${{ env.MATRIX }} \
            -f tests/e2e/out/report.json \
            --environment=true
          if [ -f tests/e2e/out/upgrade_report.json ]; then
            python .github/generate-test-artifacts.py \
              -o testartifacts-${{ env.MATRIX }} \
              -f tests/e2e/out/upgrade_report.json \
              --environment=true
          fi
      -
        name: Archive test artifacts
        if: (always() && !cancelled())
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: testartifacts-${{ env.MATRIX }}
          path: testartifacts-${{ env.MATRIX }}/
          retention-days: 10
      -
        name: Cleanup test artifacts
        if: always()
        run:
          rm -rf testartifacts-${{ env.MATRIX }}/
      -
        name: Cleanup ginkgo JSON report
        # Delete report.json after the analysis. File should always exist.
        # Delete upgrade_report.json. It may not exist depending on test level.
        if: always()
        run: |
          if [ -f tests/e2e/out/upgrade_report.json ]; then
            rm tests/e2e/out/upgrade_report.json
          fi
          if [ -f tests/e2e/out/report.json ]; then
            rm tests/e2e/out/report.json
          fi
      -
        # Archive logs for failed test cases if there are any
        name: Archive Kind logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: kind-logs-${{ matrix.id }}
          path: kind-logs/
          retention-days: 10
      -
        name: Archive e2e failure contexts
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-failure-contexts-${{ matrix.id }}
          path: |
            tests/*/out/
          retention-days: 10
          if-no-files-found: ignore

      -
        name: Archive e2e logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: cluster-logs-${{ matrix.id }}
          path: |
            tests/e2e/cluster_logs/**
          retention-days: 10
          if-no-files-found: ignore

  # Summarize E2E test results, display in the GitHub 'summary' view
  summarize-e2e-tests:
    name: E2E test suite
    needs:
      - evaluate_options
      - e2e-local
    if: |
      (always() && !cancelled()) &&
      ((
        needs.e2e-local.result == 'success' ||
        needs.e2e-local.result == 'failure'
      ) ||
      (
        needs.e2e-eks.result == 'success' ||
        needs.e2e-eks.result == 'failure'
      ) ||
      (
        needs.e2e-aks.result == 'success' ||
        needs.e2e-aks.result == 'failure'
      ) ||
      (
        needs.e2e-gke.result == 'success' ||
        needs.e2e-gke.result == 'failure'
      ) ||
      (
        needs.e2e-openshift.result == 'success' ||
        needs.e2e-openshift.result == 'failure'
      ))
    runs-on: ubuntu-24.04
    steps:
      - name: Create a directory for the artifacts
        run: mkdir test-artifacts

      - name: Download all artifacts to the directory
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: test-artifacts
          pattern: testartifacts-*

      - name: Flatten all artifacts onto directory
        # The download-artifact action, since we did not give it a name,
        # downloads all artifacts and creates a new folder for each.
        # In this step we bring all the JSONs to a single folder
        run: |
          mkdir test-artifacts/data
          mv test-artifacts/*/*.json test-artifacts/data || true

      - name: Display the structure of the artifact folder
        run: ls -R test-artifacts/data

      - name: Compute the E2E test summary
        id: generate-summary
        uses: cloudnative-pg/ciclops@f5a7b357a09f09052ec0358ac49e020f151f1653 # v1.3.1
        with:
          artifact_directory: test-artifacts/data

      - name: If there is an overflow summary, archive it
        if: steps.generate-summary.outputs.Overflow
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ steps.generate-summary.outputs.Overflow }}
          path: ${{ steps.generate-summary.outputs.Overflow }}
          retention-days: 10

      - name: Delete the downloaded files
        run: rm -rf test-artifacts
